### ISSUE TITLE
High-level tidying?

### ISSUE THREAD

**Issue by taldcroft** [sot/starcheck#311]
Looking at starcheck and being slow, l had trouble understanding installation and testing and wonder if some or all of the following cleanup would be reasonable (for a separate PR):

- Is `sandbox_starcheck` now necessary?  It now looks a lot like the actual starcheck launcher script. Maybe there are still small but important diffs?  Or can it just be replaced with a single line to call `starcheck/src/starcheck`?
- Can you remove `ska_bin_starcheck`?  Is it still being used?
- Can you remove the `install` part of `Makefile` and replace with a comment that installation is entirely via `setup.py`.
- In `Makefile` for testing do you have `$ROOT_FLIGHT` custom set outside of the Makefile?  Where is the test data?

**Comment by jeanconn** [comment]
Great ideas for rainy day.  

I do think I still like having `sandbox_starcheck` as a convenience script for testing.  Fundamentally, it is a script that sets the Python and Perl path to include the subdirectories relative to the location of the script to make it easy to run the code out of the repo for testing.  There may be ways to customize `starcheck/src/starcheck` to do the same, but I don't really see the payoff in invested time.

The other major difference between the two is that `starcheck/src/starcheck` explicitly precludes using a custom PYTHONPATH with the original flight driver that this should never be needed for flight starcheck.   It is belt-and-suspenders but not a bad idea.

`ska_bin_starcheck` is still being used.

**Comment by taldcroft** [comment]
I ran `starcheck/src/starcheck` out of the repo and it seemed to work.  Maybe I was fooling myself?  That's why I thought the sandbox might not be needed, or could just be a thin wrapper to `starcheck/src/starcheck`.  I agree that having some obvious executable in the directory is convenient.

**Comment by jeanconn** [comment]
OK, in your environment I think you have no path conflict with an installed starcheck?  The way I generally work is to test updates to starcheck using sandbox_starcheck but running against flight ska3 (which has a starcheck installed).  If I don't use the sandbox_starcheck script in that case, I think I pick up the flight libs?  Not sure if paths would be the same on osx vs linux or how much time to devote to that.

**Comment by taldcroft** [comment]
OK that makes sense.  I did not have starcheck installed.

**Comment by taldcroft** [comment]
So I think most of the questions are resolved (I'm learning!) and I can close this, except for the `$ROOT_FLIGHT` business.

**Comment by jeanconn** [comment]
Well, and we still have an action to migrate SOT MP to using, probably, the skare3 launcher and the real starcheck executable instead of the /proj/sot/ska/bin/starcheck launcher.   I think this would clear up bullets 2 and 3.

**Comment by jeanconn** [comment]
Regarding ROOT_FLIGHT, I don't have it custom set outside the Makefile, it is just broken since I commented out the include of Makefile.FLIGHT.

**Comment by jeanconn** [comment]
I think this specific ROOT_FLIGHT thing was closed with https://github.com/sot/starcheck/commit/c32b4334ad8b854c5d406df8a6ecccd250829d10 

Though in general, high-level tidying should still happen.
